import type { ModelIntelligenceModel } from "../shared";
import { MODEL_INTELLIGENCE_LAST_VERIFIED, openRouterOperationalFacts, artificialAnalysisFacts, benchmarkClaimFact, arenaSource, designArenaSource, fact, openRouterSource, vercelOperationalFacts } from "../shared";

export const FRONTIER_REGISTRY_ENTRIES: readonly ModelIntelligenceModel[] = [
  {
    id: "openai/gpt-5.4",
    name: "GPT-5.4",
    supportedGateways: ["openrouter"],
    modality: "text,image,file->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 1_050_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 1_050_000,
        inputPricePerMillion: 2.5,
        outputPricePerMillion: 15,
      }),
      ...artificialAnalysisFacts({
        slug: "gpt-5-4",
        label: "Artificial Analysis - GPT-5.4",
        intelligenceIndex: 57,
        outputTps: 78.9,
        ttftSeconds: 145.25,
        note: "Artificial Analysis benchmarks the xhigh reasoning variant on its model page.",
      }),
    ],
    lenses: [
      {
        lens: "overall_quality",
        rank: 1,
        rationale: "Highest raw intelligence score in this seeded shortlist, with frontier context and multimodal support.",
      },
      {
        lens: "research",
        rank: 2,
        rationale: "Strong long-context reasoning for synthesis-heavy work when premium latency is acceptable.",
      },
      {
        lens: "structured_output",
        rank: 3,
        rationale: "Reliable schema-heavy option when quality matters more than cost.",
      },
    ],
    derived: {
      taskFamilies: ["general", "research", "long_context", "multimodal"],
      strengths: ["Highest overall quality", "Huge context window", "Strong multimodal reasoning"],
      caveats: ["Very expensive", "High TTFT on the measured xhigh AA variant"],
      whenToUse: "Top-end general reasoning, synthesis, and high-stakes long-context work where cost is secondary.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "premium",
        quality: 3,
        speed: 2,
        cost: 0,
        reliability: 3,
      },
    },
  },
  {
    id: "openai/gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image,file->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 400_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 400_000,
        inputPricePerMillion: 0.75,
        outputPricePerMillion: 4.5,
      }),
      ...artificialAnalysisFacts({
        slug: "gpt-5-4-mini",
        label: "Artificial Analysis - GPT-5.4 mini",
        intelligenceIndex: 48,
        outputTps: 272.7,
        ttftSeconds: 5.11,
        note: "Artificial Analysis benchmarks the xhigh reasoning variant on its model page.",
      }),
    ],
    lenses: [
      {
        lens: "overall_quality",
        rank: 3,
        rationale: "High AA intelligence with much stronger speed and cost than the full GPT-5.4 frontier model.",
      },
      {
        lens: "structured_output",
        rank: 2,
        rationale: "Strong fit for strict tool- and schema-heavy work when you still want frontier-grade quality.",
      },
      {
        lens: "throughput",
        rank: 3,
        rationale: "One of the fastest high-capability reasoning models in the shortlist.",
      },
    ],
    derived: {
      taskFamilies: ["general", "coding", "agentic_coding", "multimodal"],
      strengths: ["Fast frontier model", "Reliable tools and JSON", "Good executor default"],
      caveats: ["Still meaningfully pricier than budget classifiers", "Measured TTFT is not low-latency despite high throughput"],
      whenToUse: "Balanced high-capability default for coding, tool use, and structured outputs at scale.",
      profileBuilder: {
        contextBand: "long",
        costTier: "mid",
        quality: 3,
        speed: 3,
        cost: 2,
        reliability: 3,
      },
    },
  },
  {
    id: "anthropic/claude-opus-4.6",
    name: "Claude Opus 4.6",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 1_000_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 1_000_000,
        inputPricePerMillion: 5,
        outputPricePerMillion: 25,
      }),
      ...artificialAnalysisFacts({
        slug: "claude-opus-4-6",
        label: "Artificial Analysis - Claude Opus 4.6",
        intelligenceIndex: 46,
        outputTps: 52.2,
        ttftSeconds: 2.48,
        note: "Artificial Analysis benchmarks the non-reasoning, high-effort page variant.",
      }),
      benchmarkClaimFact({
        metricId: "arena_text_overall_rank",
        label: "Arena Text Overall rank",
        value: 2,
        unit: "rank",
        source: arenaSource("/leaderboard/text/overall-no-style-control", "Arena AI - Text Arena Overall"),
      }),
      benchmarkClaimFact({
        metricId: "arena_document_rank",
        label: "Arena Document rank",
        value: 1,
        unit: "rank",
        source: arenaSource("/leaderboard/document", "Arena AI - Document Arena"),
      }),
      benchmarkClaimFact({
        metricId: "arena_search_variant_rank",
        label: "Arena Search variant rank",
        value: 2,
        unit: "rank",
        source: arenaSource("/leaderboard/search/overall-add-style-control", "Arena AI - Search Arena"),
        note: "The live Arena row is for the search-specific variant `claude-opus-4-6-search`, used here as a capability signal rather than a deployable gateway ID.",
      }),
      benchmarkClaimFact({
        metricId: "designarena_code_categories_elo",
        label: "DesignArena Code Categories Elo",
        value: 1374,
        unit: "elo",
        source: designArenaSource("/leaderboard/code", "DesignArena - Code Categories"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_website_elo",
        label: "DesignArena Website Elo",
        value: 1374,
        unit: "elo",
        source: designArenaSource("/leaderboard/website", "DesignArena - Website"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_ui_component_elo",
        label: "DesignArena UI Component Elo",
        value: 1397,
        unit: "elo",
        source: designArenaSource("/leaderboard/ui-components", "DesignArena - UI Components"),
      }),
    ],
    lenses: [
      {
        lens: "overall_quality",
        rank: 2,
        rationale: "Premium frontier model with strong reasoning and sustained professional-work positioning.",
      },
      {
        lens: "coding_quality",
        rank: 3,
        rationale: "Capability-first coding choice when cost is secondary to judgment and persistence.",
      },
      {
        lens: "frontend_ui",
        rank: 1,
        rationale: "Current DesignArena leader across code categories, website generation, and UI components.",
      },
    ],
    derived: {
      taskFamilies: ["general", "coding", "agentic_coding", "research", "multimodal"],
      strengths: ["Premium reasoning", "Large-context professional work", "Strong multimodal judgment", "Best current frontend/UI benchmark leader"],
      caveats: ["Most expensive mainstream option", "Low throughput relative to cheaper coding models"],
      whenToUse: "Highest-stakes reasoning, frontend architecture, and long-form professional work where cost can be ignored.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "premium",
        quality: 3,
        speed: 1,
        cost: 0,
        reliability: 3,
      },
    },
  },
  {
    id: "openai/o3-deep-research",
    name: "o3 Deep Research",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image,file->text",
    openSource: false,
    structuredOutput: false,
    toolUse: true,
    vision: true,
    contextWindow: 200_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 200_000,
        inputPricePerMillion: 10,
        outputPricePerMillion: 40,
      }),
      fact({
        metricId: "openrouter_web_search_price_per_1k_calls",
        label: "OpenRouter web search price",
        kind: "cost",
        value: 5,
        unit: "usd_per_1k_calls",
        direction: "lower_better",
        source: openRouterSource(),
        note: "OpenRouter documents additional `web_search` cost for this model.",
      }),
    ],
    lenses: [
      {
        lens: "research",
        rank: 5,
        rationale: "Explicit deep-research specialist when you want OpenAI's dedicated web synthesis workflow rather than a general-purpose frontier model.",
      },
    ],
    derived: {
      taskFamilies: ["research", "general", "long_context", "multimodal"],
      strengths: ["Purpose-built deep research", "Web-grounded synthesis", "File and vision inputs"],
      caveats: ["Very expensive", "Always incurs web-search cost", "Not a general routing default or classifier choice"],
      whenToUse: "Deep research, multi-step web synthesis, and report-style investigation when you want OpenAI's dedicated research workflow.",
      profileBuilder: {
        contextBand: "long",
        costTier: "premium",
        quality: 3,
        speed: 1,
        cost: 0,
        reliability: 2,
      },
    },
  },
  {
    id: "anthropic/claude-sonnet-4.6",
    name: "Claude Sonnet 4.6",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 1_000_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 1_000_000,
        inputPricePerMillion: 3,
        outputPricePerMillion: 15,
      }),
      ...artificialAnalysisFacts({
        slug: "claude-sonnet-4-6",
        label: "Artificial Analysis - Claude Sonnet 4.6",
        intelligenceIndex: 44,
        outputTps: 53.2,
        ttftSeconds: 1.67,
        note: "Artificial Analysis benchmarks the non-reasoning, high-effort page variant.",
      }),
      benchmarkClaimFact({
        metricId: "arena_document_rank",
        label: "Arena Document rank",
        value: 2,
        unit: "rank",
        source: arenaSource("/leaderboard/document", "Arena AI - Document Arena"),
      }),
      benchmarkClaimFact({
        metricId: "arena_search_variant_rank",
        label: "Arena Search variant rank",
        value: 10,
        unit: "rank",
        source: arenaSource("/leaderboard/search/overall-add-style-control", "Arena AI - Search Arena"),
        note: "The live Arena row is for the search-specific variant `claude-sonnet-4-6-search`, used here as a capability signal rather than a deployable gateway ID.",
      }),
      benchmarkClaimFact({
        metricId: "designarena_code_categories_elo",
        label: "DesignArena Code Categories Elo",
        value: 1346,
        unit: "elo",
        source: designArenaSource("/leaderboard/code", "DesignArena - Code Categories"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_website_elo",
        label: "DesignArena Website Elo",
        value: 1347,
        unit: "elo",
        source: designArenaSource("/leaderboard/website", "DesignArena - Website"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_ui_component_elo",
        label: "DesignArena UI Component Elo",
        value: 1358,
        unit: "elo",
        source: designArenaSource("/leaderboard/ui-components", "DesignArena - UI Components"),
      }),
    ],
    lenses: [
      {
        lens: "coding_quality",
        rank: 2,
        rationale: "High-confidence coding and review choice with better cost-quality balance than Opus.",
      },
      {
        lens: "multimodal",
        rank: 4,
        rationale: "Strong visual and document work with dependable instruction following.",
      },
      {
        lens: "frontend_ui",
        rank: 2,
        rationale: "Most balanced premium frontend implementation model after Opus, with top-three DesignArena website and UI component performance.",
      },
    ],
    derived: {
      taskFamilies: ["general", "coding", "agentic_coding", "support", "multimodal"],
      strengths: ["Strong coding judgment", "Solid review quality", "Reliable all-purpose premium-mid option", "Consistent top-tier frontend implementation"],
      caveats: ["Still costly for large-scale classifier work", "Not a speed-first model"],
      whenToUse: "Capability-first default for nuanced coding, frontend implementation, design-heavy tasks, and multimodal support work.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "mid",
        quality: 3,
        speed: 2,
        cost: 1,
        reliability: 3,
      },
    },
  },
  {
    id: "anthropic/claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 200_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 200_000,
        inputPricePerMillion: 1,
        outputPricePerMillion: 5,
      }),
      ...artificialAnalysisFacts({
        slug: "claude-4-5-haiku",
        label: "Artificial Analysis - Claude Haiku 4.5",
        intelligenceIndex: 31,
        outputTps: 104,
        ttftSeconds: 0.68,
        note: "Artificial Analysis benchmarks the Claude 4.5 Haiku page variant.",
      }),
    ],
    lenses: [
      {
        lens: "classifier_candidate",
        rank: 3,
        rationale: "Fast, reliable Claude-family option when you want better responsiveness without dropping into budget-tier models.",
      },
      {
        lens: "ttft",
        rank: 4,
        rationale: "Very low measured TTFT for a high-reliability multimodal model.",
      },
    ],
    derived: {
      taskFamilies: ["general", "support", "coding", "multimodal"],
      strengths: ["Fast Claude option", "Low TTFT", "Good instruction following"],
      caveats: ["More expensive than Gemini Flash Lite", "Not the cheapest classifier path"],
      whenToUse: "Fast general-purpose reasoning when you want Claude-family behavior at lower latency and cost.",
      profileBuilder: {
        contextBand: "long",
        costTier: "efficient",
        quality: 2,
        speed: 3,
        cost: 2,
        reliability: 3,
      },
    },
  },
  {
    id: "google/gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image,file,audio,video->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 1_048_576,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 1_048_576,
        inputPricePerMillion: 2,
        outputPricePerMillion: 12,
      }),
      ...artificialAnalysisFacts({
        slug: "gemini-3-1-pro-preview",
        label: "Artificial Analysis - Gemini 3.1 Pro Preview",
        intelligenceIndex: 57,
        outputTps: 120.3,
        ttftSeconds: 39.08,
        note: "Artificial Analysis benchmarks the Gemini 3.1 Pro Preview page variant.",
      }),
      benchmarkClaimFact({
        metricId: "arena_text_overall_rank",
        label: "Arena Text Overall rank",
        value: 3,
        unit: "rank",
        source: arenaSource("/leaderboard/text/overall-no-style-control", "Arena AI - Text Arena Overall"),
      }),
      benchmarkClaimFact({
        metricId: "arena_document_rank",
        label: "Arena Document rank",
        value: 5,
        unit: "rank",
        source: arenaSource("/leaderboard/document", "Arena AI - Document Arena"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_code_categories_elo",
        label: "DesignArena Code Categories Elo",
        value: 1312,
        unit: "elo",
        source: designArenaSource("/leaderboard/code", "DesignArena - Code Categories"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_website_elo",
        label: "DesignArena Website Elo",
        value: 1303,
        unit: "elo",
        source: designArenaSource("/leaderboard/website", "DesignArena - Website"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_ui_component_elo",
        label: "DesignArena UI Component Elo",
        value: 1354,
        unit: "elo",
        source: designArenaSource("/leaderboard/ui-components", "DesignArena - UI Components"),
      }),
    ],
    lenses: [
      {
        lens: "research",
        rank: 1,
        rationale: "Strongest quality-first research and synthesis option in the refreshed registry, pairing 1M context with top-tier reasoning.",
      },
      {
        lens: "long_context",
        rank: 2,
        rationale: "Best depth-first 1M-context option when you want stronger reasoning than the faster Flash line.",
      },
      {
        lens: "multimodal",
        rank: 2,
        rationale: "Premium multimodal choice for file, audio, image, video, and tool-heavy workflows.",
      },
      {
        lens: "frontend_ui",
        rank: 5,
        rationale: "Strong premium frontend model with solid DesignArena website and UI component scores, but behind Opus, Sonnet, GLM 5, and Gemini 3 Pro on current results.",
      },
    ],
    derived: {
      taskFamilies: ["research", "long_context", "general", "multimodal", "agentic_coding"],
      strengths: ["Top-tier reasoning quality", "1M context window", "Strong agentic and multimodal workflows", "Good frontend/UI benchmark results"],
      caveats: ["Very high measured TTFT", "Premium pricing"],
      whenToUse: "Complex reasoning, high-context research, frontend planning, and agentic coding where quality matters more than latency.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "premium",
        quality: 3,
        speed: 1,
        cost: 0,
        reliability: 3,
      },
    },
  },
];
