import type { ModelIntelligenceModel } from "../shared";
import { MODEL_INTELLIGENCE_LAST_VERIFIED, openRouterOperationalFacts, artificialAnalysisFacts, benchmarkClaimFact, arenaSource, designArenaSource, fact, openRouterSource, vercelOperationalFacts } from "../shared";

export const IMAGE_AND_OPEN_REGISTRY_ENTRIES: readonly ModelIntelligenceModel[] = [
  {
    id: "openai/gpt-5-image",
    name: "GPT-5 Image",
    supportedGateways: ["openrouter"],
    modality: "text,image,file->text,image",
    openSource: false,
    structuredOutput: false,
    toolUse: false,
    vision: true,
    contextWindow: 400_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 400_000,
        inputPricePerMillion: 10,
        outputPricePerMillion: 10,
      }),
      benchmarkClaimFact({
        metricId: "arena_text_to_image_rank",
        label: "Arena Text-to-Image rank",
        value: 2,
        unit: "rank",
        source: arenaSource("/leaderboard/text-to-image", "Arena AI - Text-to-Image Arena"),
        note: "Arena's strongest current OpenAI image row is `gpt-image-1.5-high-fidelity`; this entry tracks the currently deployable OpenRouter flagship image model.",
      }),
    ],
    lenses: [
      {
        lens: "image_generation",
        rank: 5,
        rationale: "Premium OpenAI image lane when you want the OpenRouter-native flagship rather than the cheaper or more recent image specialists.",
      },
    ],
    derived: {
      taskFamilies: ["multimodal", "general"],
      strengths: ["Image generation", "OpenAI multimodal stack", "High-quality creative output"],
      caveats: ["Expensive", "Not a text-first routing default"],
      whenToUse: "Premium image generation and detailed image-editing workflows when image quality is the primary goal.",
      profileBuilder: {
        contextBand: "long",
        costTier: "premium",
        quality: 3,
        speed: 1,
        cost: 0,
        reliability: 2,
      },
    },
  },
  {
    id: "google/gemini-3.1-flash-image-preview",
    name: "Gemini 3.1 Flash Image Preview",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image->text,image",
    openSource: false,
    structuredOutput: false,
    toolUse: false,
    vision: true,
    contextWindow: 65_536,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 65_536,
        inputPricePerMillion: 0.5,
        outputPricePerMillion: 3,
      }),
      benchmarkClaimFact({
        metricId: "arena_text_to_image_rank",
        label: "Arena Text-to-Image rank",
        value: 1,
        unit: "rank",
        source: arenaSource("/leaderboard/text-to-image", "Arena AI - Text-to-Image Arena"),
      }),
      benchmarkClaimFact({
        metricId: "arena_image_edit_rank",
        label: "Arena Image Edit rank",
        value: 4,
        unit: "rank",
        source: arenaSource("/leaderboard/image-edit", "Arena AI - Image Edit Arena"),
      }),
    ],
    lenses: [
      {
        lens: "image_generation",
        rank: 1,
        rationale: "Best current blend of price and leaderboard performance across text-to-image and image-edit workflows.",
      },
    ],
    derived: {
      taskFamilies: ["multimodal"],
      strengths: ["Top-ranked current text-to-image pick", "Strong image editing", "Cheaper than premium image specialists"],
      caveats: ["Image-generation specialist, not a text-routing default", "65K context is far shorter than text-first Gemini models"],
      whenToUse: "Fast, high-value image generation and iterative image editing when you want the current Gemini image leader.",
      profileBuilder: {
        contextBand: "standard",
        costTier: "mid",
        quality: 1,
        speed: 1,
        cost: 1,
        reliability: 1,
      },
    },
  },
  {
    id: "google/gemini-3-pro-image-preview",
    name: "Gemini 3 Pro Image Preview",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image->text,image",
    openSource: false,
    structuredOutput: false,
    toolUse: false,
    vision: true,
    contextWindow: 65_536,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 65_536,
        inputPricePerMillion: 2,
        outputPricePerMillion: 12,
      }),
      benchmarkClaimFact({
        metricId: "arena_text_to_image_rank",
        label: "Arena Text-to-Image rank",
        value: 3,
        unit: "rank",
        source: arenaSource("/leaderboard/text-to-image", "Arena AI - Text-to-Image Arena"),
      }),
      benchmarkClaimFact({
        metricId: "arena_image_edit_rank",
        label: "Arena Image Edit rank",
        value: 2,
        unit: "rank",
        source: arenaSource("/leaderboard/image-edit", "Arena AI - Image Edit Arena"),
      }),
    ],
    lenses: [
      {
        lens: "image_generation",
        rank: 2,
        rationale: "Premium image-edit and design-focused Gemini lane when you want higher-fidelity visual control than the cheaper Flash image model.",
      },
    ],
    derived: {
      taskFamilies: ["multimodal"],
      strengths: ["Premium image-edit quality", "Studio-style controls", "Strong text rendering and composition"],
      caveats: ["Expensive", "Specialized image model rather than a text assistant"],
      whenToUse: "High-fidelity image generation, design work, and premium image editing where visual quality matters more than cost.",
      profileBuilder: {
        contextBand: "standard",
        costTier: "premium",
        quality: 1,
        speed: 1,
        cost: 0,
        reliability: 1,
      },
    },
  },
  {
    id: "openai/gpt-image-1.5",
    name: "GPT Image 1.5",
    supportedGateways: ["vercel"],
    modality: "text,image->text,image",
    openSource: false,
    structuredOutput: false,
    toolUse: false,
    vision: true,
    contextWindow: 400_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...vercelOperationalFacts({
        contextWindow: 400_000,
        inputPricePerMillion: 5,
        outputPricePerMillion: 32,
      }),
      benchmarkClaimFact({
        metricId: "arena_text_to_image_rank",
        label: "Arena Text-to-Image rank",
        value: 2,
        unit: "rank",
        source: arenaSource("/leaderboard/text-to-image", "Arena AI - Text-to-Image Arena"),
        note: "Arena's strongest current OpenAI image row is `gpt-image-1.5-high-fidelity`; this entry tracks the deployable Vercel image model family.",
      }),
      benchmarkClaimFact({
        metricId: "arena_image_edit_rank",
        label: "Arena Image Edit rank",
        value: 5,
        unit: "rank",
        source: arenaSource("/leaderboard/image-edit", "Arena AI - Image Edit Arena"),
      }),
    ],
    lenses: [
      {
        lens: "image_generation",
        rank: 3,
        rationale: "Best current Vercel-native OpenAI image lane when you want stronger instruction adherence and OpenAI-style editing behavior.",
      },
    ],
    derived: {
      taskFamilies: ["multimodal"],
      strengths: ["Strong prompt adherence", "High-quality OpenAI image lane", "Good text-to-image performance"],
      caveats: ["Vercel-only exact ID", "Expensive output pricing"],
      whenToUse: "OpenAI-native image generation and editing on Vercel when prompt adherence and output quality matter more than cost.",
      profileBuilder: {
        contextBand: "long",
        costTier: "premium",
        quality: 1,
        speed: 1,
        cost: 0,
        reliability: 1,
      },
    },
  },
  {
    id: "perplexity/sonar-pro-search",
    name: "Sonar Pro Search",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image->text",
    openSource: false,
    structuredOutput: true,
    toolUse: false,
    vision: true,
    contextWindow: 200_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 200_000,
        inputPricePerMillion: 3,
        outputPricePerMillion: 15,
      }),
      benchmarkClaimFact({
        metricId: "arena_search_rank",
        label: "Arena Search rank",
        value: 16,
        unit: "rank",
        source: arenaSource("/leaderboard/search/overall-add-style-control", "Arena AI - Search Arena"),
        note: "The live Arena row is `ppl-sonar-pro-high`; this entry tracks the closest gateway-deployable Perplexity Pro Search model family.",
      }),
    ],
    lenses: [
      {
        lens: "research",
        rank: 4,
        rationale: "Explicit search-grounded research model when you want Perplexity-style retrieval and synthesis over a general-purpose frontier model.",
      },
    ],
    derived: {
      taskFamilies: ["research", "general", "support"],
      strengths: ["Search-grounded answers", "Strong follow-up handling", "Purpose-built research workflow"],
      caveats: ["Search-specialized rather than a general default", "Premium token pricing plus request-based search costs on OpenRouter"],
      whenToUse: "Web-grounded research, synthesis, and follow-up question answering when you want a dedicated search model instead of a generalist with tools.",
      profileBuilder: {
        contextBand: "long",
        costTier: "mid",
        quality: 2,
        speed: 2,
        cost: 1,
        reliability: 2,
      },
    },
  },
  {
    id: "qwen/qwen3.5-397b-a17b",
    name: "Qwen3.5 397B A17B",
    supportedGateways: ["openrouter"],
    modality: "text,image,video->text",
    openSource: true,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 262_144,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 262_144,
        inputPricePerMillion: 0.39,
        outputPricePerMillion: 2.34,
      }),
      ...artificialAnalysisFacts({
        slug: "qwen3-5-397b-a17b",
        label: "Artificial Analysis - Qwen3.5 397B A17B",
        intelligenceIndex: 45,
        outputTps: 81.7,
        ttftSeconds: 2.65,
        note: "Artificial Analysis benchmarks the Qwen3.5 397B A17B reasoning page variant.",
      }),
    ],
    lenses: [
      {
        lens: "open_source",
        rank: 2,
        rationale: "Highest-capability Qwen 3.5 open-weight option in the registry, with strong multimodal and agentic coverage.",
      },
      {
        lens: "multimodal",
        rank: 2,
        rationale: "Best open-weight multimodal alternative when you want Qwen 3.5 vision and video support in one pool.",
      },
    ],
    derived: {
      taskFamilies: ["general", "coding", "agentic_coding", "multimodal", "research"],
      strengths: ["Strong open-weight reasoning", "Vision and video support", "Long 262K context"],
      caveats: ["OpenRouter-only exact ID", "More expensive than the smaller Qwen 3.5 variants"],
      whenToUse: "Best open-weight Qwen pick for high-capability multimodal, coding, and agent workflows.",
      profileBuilder: {
        contextBand: "long",
        costTier: "efficient",
        quality: 3,
        speed: 2,
        cost: 2,
        reliability: 2,
      },
    },
  },
  {
    id: "qwen/qwen3.5-122b-a10b",
    name: "Qwen3.5 122B A10B",
    supportedGateways: ["openrouter"],
    modality: "text,image,video->text",
    openSource: true,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 262_144,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 262_144,
        inputPricePerMillion: 0.26,
        outputPricePerMillion: 2.08,
      }),
      ...artificialAnalysisFacts({
        slug: "qwen3-5-122b-a10b",
        label: "Artificial Analysis - Qwen3.5 122B A10B",
        intelligenceIndex: 42,
        outputTps: 153.4,
        ttftSeconds: 2.31,
        note: "Artificial Analysis benchmarks the Qwen3.5 122B A10B reasoning page variant.",
      }),
    ],
    lenses: [
      {
        lens: "coding_value",
        rank: 2,
        rationale: "Best open-weight value coding pick after MiniMax, combining strong quality with much lower cost than the 397B flagship.",
      },
      {
        lens: "open_source",
        rank: 3,
        rationale: "Strong open-weight generalist when you want Qwen 3.5 capability without paying 397B pricing.",
      },
    ],
    derived: {
      taskFamilies: ["coding", "agentic_coding", "general", "multimodal"],
      strengths: ["Strong value-performance balance", "Fast for its size", "Vision and video support"],
      caveats: ["OpenRouter-only exact ID", "Still not a budget-tier classifier"],
      whenToUse: "Open-weight coding and multimodal work when you want a strong Qwen 3.5 option with better cost-efficiency than 397B.",
      profileBuilder: {
        contextBand: "long",
        costTier: "efficient",
        quality: 2,
        speed: 3,
        cost: 2,
        reliability: 2,
      },
    },
  },
  {
    id: "qwen/qwen3.5-27b",
    name: "Qwen3.5 27B",
    supportedGateways: ["openrouter"],
    modality: "text,image,video->text",
    openSource: true,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 262_144,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 262_144,
        inputPricePerMillion: 0.195,
        outputPricePerMillion: 1.56,
      }),
      ...artificialAnalysisFacts({
        slug: "qwen3-5-27b",
        label: "Artificial Analysis - Qwen3.5 27B",
        intelligenceIndex: 42,
        outputTps: 87.6,
        ttftSeconds: 5.62,
        note: "Artificial Analysis benchmarks the Qwen3.5 27B reasoning page variant.",
      }),
    ],
    lenses: [
      {
        lens: "budget_text",
        rank: 3,
        rationale: "Cheapest Qwen 3.5 entry in the registry when you want open-weight multimodal breadth without the larger-MoE price.",
      },
      {
        lens: "open_source",
        rank: 6,
        rationale: "Smallest Qwen 3.5 registry entry with the easiest price profile.",
      },
    ],
    derived: {
      taskFamilies: ["general", "support", "multimodal", "coding"],
      strengths: ["Cheap open-weight multimodal option", "262K context", "Qwen 3.5 series capabilities"],
      caveats: ["Slower TTFT than the larger 122B variant", "Lower headroom on hard reasoning than 397B or 122B"],
      whenToUse: "Budget-conscious open-weight multimodal and general-purpose work where Qwen 3.5 features matter more than frontier depth.",
      profileBuilder: {
        contextBand: "long",
        costTier: "budget",
        quality: 2,
        speed: 2,
        cost: 3,
        reliability: 2,
      },
    },
  },
];
