import type { ModelIntelligenceModel } from "../shared";
import { MODEL_INTELLIGENCE_LAST_VERIFIED, openRouterOperationalFacts, artificialAnalysisFacts, benchmarkClaimFact, arenaSource, designArenaSource, fact, openRouterSource, vercelOperationalFacts } from "../shared";

export const SPEED_AND_SPECIALIST_REGISTRY_ENTRIES: readonly ModelIntelligenceModel[] = [
  {
    id: "x-ai/grok-4.20-beta",
    name: "Grok 4.20 Beta",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 2_000_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 2_000_000,
        inputPricePerMillion: 2,
        outputPricePerMillion: 6,
      }),
      ...artificialAnalysisFacts({
        slug: "grok-4-20",
        label: "Artificial Analysis - Grok 4.20 Beta",
        intelligenceIndex: 48,
        outputTps: 211.2,
        ttftSeconds: 13.54,
        note: "Artificial Analysis benchmarks the Grok 4.20 page variant.",
      }),
      benchmarkClaimFact({
        metricId: "arena_text_overall_rank",
        label: "Arena Text Overall rank",
        value: 4,
        unit: "rank",
        source: arenaSource("/leaderboard/text/overall-no-style-control", "Arena AI - Text Arena Overall"),
        note: "Arena marks the current Grok 4.20 row as preliminary.",
      }),
      benchmarkClaimFact({
        metricId: "arena_search_variant_rank",
        label: "Arena Search variant rank",
        value: 1,
        unit: "rank",
        source: arenaSource("/leaderboard/search/overall-add-style-control", "Arena AI - Search Arena"),
        note: "The live Arena row is for the search-tuned variant `grok-4.20-beta1`, used here as a capability signal rather than a deployable gateway ID.",
      }),
    ],
    lenses: [
      {
        lens: "long_context",
        rank: 3,
        rationale: "2M context flagship option when you want much stronger raw quality than the fast Grok 4.1 line.",
      },
      {
        lens: "overall_quality",
        rank: 5,
        rationale: "High intelligence, 2M context, and agentic tool support make it a strong frontier alternative outside the OpenAI and Anthropic stack.",
      },
    ],
    derived: {
      taskFamilies: ["general", "research", "long_context", "multimodal", "agentic_coding"],
      strengths: ["2M context frontier model", "Strong agentic tool calling", "High measured throughput for its class"],
      caveats: ["Premium pricing", "Measured TTFT is much slower than Grok 4.1 Fast"],
      whenToUse: "Large-context agentic work, search-heavy operations, and long-horizon reasoning when you want xAI's flagship instead of the fast budget Grok line.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "mid",
        quality: 3,
        speed: 2,
        cost: 1,
        reliability: 2,
      },
    },
  },
  {
    id: "x-ai/grok-4.1-fast",
    name: "Grok 4.1 Fast",
    supportedGateways: ["openrouter"],
    modality: "text,image->text",
    openSource: false,
    structuredOutput: false,
    toolUse: true,
    vision: true,
    contextWindow: 2_000_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 2_000_000,
        inputPricePerMillion: 0.2,
        outputPricePerMillion: 0.5,
      }),
      ...artificialAnalysisFacts({
        slug: "grok-4-1-fast",
        label: "Artificial Analysis - Grok 4.1 Fast",
        intelligenceIndex: 24,
        outputTps: 155.3,
        ttftSeconds: 0.56,
        note: "Artificial Analysis benchmarks the non-reasoning page variant.",
      }),
    ],
    lenses: [
      {
        lens: "long_context",
        rank: 1,
        rationale: "Largest context window in the shortlist with excellent TTFT and strong practical throughput.",
      },
      {
        lens: "ttft",
        rank: 3,
        rationale: "Near-best TTFT with an unusually large 2M context window.",
      },
    ],
    derived: {
      taskFamilies: ["general", "support", "long_context", "multimodal"],
      strengths: ["2M context window", "Very low TTFT", "Good cost-speed ratio"],
      caveats: ["Structured-output reliability is not the primary reason to pick it", "OpenRouter-only exact ID"],
      whenToUse: "Very long-context and tool-heavy operational work when you want a fast model with huge window size.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "budget",
        quality: 2,
        speed: 3,
        cost: 3,
        reliability: 1,
      },
    },
  },
  {
    id: "x-ai/grok-4.20-multi-agent-beta",
    name: "Grok 4.20 Multi-Agent Beta",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 2_000_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 2_000_000,
        inputPricePerMillion: 2,
        outputPricePerMillion: 6,
      }),
      benchmarkClaimFact({
        metricId: "arena_search_rank",
        label: "Arena Search rank",
        value: 1,
        unit: "rank",
        source: arenaSource("/leaderboard/search/overall-add-style-control", "Arena AI - Search Arena"),
        note: "Arena ranks the closest live Grok 4.20 search variant first overall; this deployable multi-agent beta is the cleanest gateway-available deep-research sibling.",
      }),
    ],
    lenses: [
      {
        lens: "research",
        rank: 3,
        rationale: "Best explicit deep-research / multi-agent xAI option when you want long-horizon browsing and synthesis.",
      },
      {
        lens: "long_context",
        rank: 4,
        rationale: "2M context and agent parallelism make it a useful long-context research specialist.",
      },
    ],
    derived: {
      taskFamilies: ["research", "general", "long_context", "agentic_coding", "multimodal"],
      strengths: ["Deep research workflow", "Parallel multi-agent synthesis", "2M context with strong tool support"],
      caveats: ["Premium pricing", "Specialized research-oriented variant rather than a generic default"],
      whenToUse: "Search-heavy research, multi-step synthesis, and multi-agent investigation when you want a dedicated deep-research model.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "mid",
        quality: 3,
        speed: 2,
        cost: 1,
        reliability: 2,
      },
    },
  },
  {
    id: "xai/grok-4.1-fast-non-reasoning",
    name: "Grok 4.1 Fast Non-Reasoning",
    supportedGateways: ["vercel"],
    modality: "text->text",
    openSource: false,
    structuredOutput: false,
    toolUse: true,
    vision: false,
    contextWindow: 2_000_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...vercelOperationalFacts({
        contextWindow: 2_000_000,
        inputPricePerMillion: 0.2,
        outputPricePerMillion: 0.5,
      }),
      ...artificialAnalysisFacts({
        slug: "grok-4-1-fast",
        label: "Artificial Analysis - Grok 4.1 Fast",
        intelligenceIndex: 24,
        outputTps: 155.3,
        ttftSeconds: 0.56,
        note: "Artificial Analysis covers the Grok 4.1 Fast non-reasoning variant; this maps directly to Vercel's text-only deployable ID.",
      }),
    ],
    lenses: [
      {
        lens: "long_context",
        rank: 2,
        rationale: "Best exact Vercel-only long-context speed option for text-heavy routing pools.",
      },
    ],
    derived: {
      taskFamilies: ["general", "support", "long_context"],
      strengths: ["2M text context", "Fast reflex model on Vercel", "Low-cost operational lookups"],
      caveats: ["Text-only variant", "Not a structured-output specialist"],
      whenToUse: "Vercel-only long-context text workflows where speed and context matter more than multimodal or schema-heavy behavior.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "budget",
        quality: 1,
        speed: 3,
        cost: 3,
        reliability: 1,
      },
    },
  },
  {
    id: "xai/grok-code-fast-1",
    name: "Grok Code Fast 1",
    supportedGateways: ["vercel"],
    modality: "text->text",
    openSource: false,
    structuredOutput: false,
    toolUse: true,
    vision: false,
    contextWindow: 256_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...vercelOperationalFacts({
        contextWindow: 256_000,
        inputPricePerMillion: 0.2,
        outputPricePerMillion: 1.5,
      }),
      ...artificialAnalysisFacts({
        slug: "grok-code-fast-1",
        label: "Artificial Analysis - Grok Code Fast 1",
        intelligenceIndex: 29,
        outputTps: 201.1,
        ttftSeconds: 3.44,
        note: "Artificial Analysis benchmarks the Grok Code Fast 1 page variant.",
      }),
    ],
    lenses: [
      {
        lens: "coding_value",
        rank: 3,
        rationale: "Fast budget-conscious coding option on Vercel with strong measured throughput.",
      },
    ],
    derived: {
      taskFamilies: ["coding", "agentic_coding"],
      strengths: ["Fast coding loop", "Cheap Vercel coding option", "Strong measured throughput"],
      caveats: ["TTFT is not best-in-class", "Structured output is not the main selling point"],
      whenToUse: "Fast, lower-cost coding on Vercel when exact frontier coding quality is not required.",
      profileBuilder: {
        contextBand: "long",
        costTier: "budget",
        quality: 2,
        speed: 3,
        cost: 3,
        reliability: 2,
      },
    },
  },
  {
    id: "minimax/minimax-m2.7",
    name: "MiniMax M2.7",
    supportedGateways: ["openrouter"],
    modality: "text->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: false,
    contextWindow: 204_800,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 204_800,
        inputPricePerMillion: 0.3,
        outputPricePerMillion: 1.2,
      }),
      ...artificialAnalysisFacts({
        slug: "minimax-m2-7",
        label: "Artificial Analysis - MiniMax-M2.7",
        intelligenceIndex: 50,
        outputTps: 49.7,
        ttftSeconds: 3.05,
        note: "Artificial Analysis benchmarks the MiniMax-M2.7 page variant.",
      }),
      benchmarkClaimFact({
        metricId: "openrouter_swe_pro_pct",
        label: "Reported SWE-Pro",
        value: 56.2,
        unit: "percent",
        source: openRouterSource(),
        note: "OpenRouter model description cites 56.2% on SWE-Pro.",
      }),
      benchmarkClaimFact({
        metricId: "openrouter_terminal_bench_2_pct",
        label: "Reported Terminal Bench 2",
        value: 57,
        unit: "percent",
        source: openRouterSource(),
        note: "OpenRouter model description cites 57.0% on Terminal Bench 2.",
      }),
      benchmarkClaimFact({
        metricId: "openrouter_gdpval_aa_elo",
        label: "Reported GDPval-AA Elo",
        value: 1495,
        unit: "elo",
        source: openRouterSource(),
        note: "OpenRouter model description cites a 1495 Elo on GDPval-AA.",
      }),
    ],
    lenses: [
      {
        lens: "coding_value",
        rank: 1,
        rationale: "Best price-to-performance coding choice in the current shortlist, with strong cited agentic coding benchmarks.",
      },
      {
        lens: "overall_quality",
        rank: 4,
        rationale: "Very high measured intelligence for its price tier even before accounting for value.",
      },
    ],
    derived: {
      taskFamilies: ["coding", "agentic_coding", "general"],
      strengths: ["Excellent coding value", "Strong cited agentic benchmarks", "High AA intelligence for the price"],
      caveats: ["Not a latency-first choice", "OpenRouter-only exact ID"],
      whenToUse: "Primary coding value pick when you want frontier-adjacent agentic coding without paying premium output prices.",
      profileBuilder: {
        contextBand: "long",
        costTier: "efficient",
        quality: 3,
        speed: 2,
        cost: 2,
        reliability: 2,
      },
    },
  },
  {
    id: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    supportedGateways: ["openrouter"],
    modality: "text,image->text",
    openSource: true,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 262_144,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 262_144,
        inputPricePerMillion: 0.45,
        outputPricePerMillion: 2.2,
      }),
      ...artificialAnalysisFacts({
        slug: "kimi-k2-5",
        label: "Artificial Analysis - Kimi K2.5",
        intelligenceIndex: 47,
        outputTps: 47.1,
        ttftSeconds: 2.81,
        note: "Artificial Analysis benchmarks the reasoning page variant.",
      }),
      benchmarkClaimFact({
        metricId: "designarena_code_categories_elo",
        label: "DesignArena Code Categories Elo",
        value: 1325,
        unit: "elo",
        source: designArenaSource("/leaderboard/code", "DesignArena - Code Categories"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_website_elo",
        label: "DesignArena Website Elo",
        value: 1325,
        unit: "elo",
        source: designArenaSource("/leaderboard/website", "DesignArena - Website"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_ui_component_elo",
        label: "DesignArena UI Component Elo",
        value: 1324,
        unit: "elo",
        source: designArenaSource("/leaderboard/ui-components", "DesignArena - UI Components"),
      }),
    ],
    lenses: [
      {
        lens: "open_source",
        rank: 4,
        rationale: "High-intelligence open-weight option with multimodal and tool-use coverage.",
      },
      {
        lens: "multimodal",
        rank: 3,
        rationale: "Useful open-weight multimodal alternative when you want tool use plus vision in one pool.",
      },
      {
        lens: "frontend_ui",
        rank: 6,
        rationale: "Good open-weight frontend and website performer, but it trails GLM 5 and the top proprietary models on current DesignArena results.",
      },
    ],
    derived: {
      taskFamilies: ["general", "research", "multimodal", "agentic_coding"],
      strengths: ["Open weights", "Strong AA intelligence", "Vision plus tool use", "Solid frontend and website performance"],
      caveats: ["Not fast", "More expensive than DeepSeek for plain text volume"],
      whenToUse: "Open-weight multimodal, frontend/UI iteration, and agentic workflows where you want stronger quality than budget open models.",
      profileBuilder: {
        contextBand: "long",
        costTier: "efficient",
        quality: 3,
        speed: 1,
        cost: 2,
        reliability: 2,
      },
    },
  },
  {
    id: "inception/mercury-2",
    name: "Mercury 2",
    supportedGateways: ["openrouter"],
    modality: "text->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: false,
    contextWindow: 128_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 128_000,
        inputPricePerMillion: 0.25,
        outputPricePerMillion: 0.75,
      }),
      ...artificialAnalysisFacts({
        slug: "mercury-2",
        label: "Artificial Analysis - Mercury 2",
        intelligenceIndex: 33,
        outputTps: 1021.5,
        ttftSeconds: 4.36,
        note: "Artificial Analysis benchmarks the Mercury 2 page variant.",
      }),
    ],
    lenses: [
      {
        lens: "throughput",
        rank: 1,
        rationale: "Clear throughput winner in the shortlist with measured 1,021.5 tokens/sec.",
      },
      {
        lens: "budget_text",
        rank: 2,
        rationale: "Great value for fast operational text workloads when raw throughput matters more than top-end reasoning depth.",
      },
    ],
    derived: {
      taskFamilies: ["general", "coding", "support"],
      strengths: ["Best throughput", "Cheap text generation", "Structured output and tools"],
      caveats: ["High TTFT despite huge throughput", "No vision support"],
      whenToUse: "Fastest text generation for agent loops, coding churn, and high-throughput operational workloads.",
      profileBuilder: {
        contextBand: "standard",
        costTier: "budget",
        quality: 2,
        speed: 3,
        cost: 3,
        reliability: 2,
      },
    },
  },
];
