import type { ModelIntelligenceModel } from "../shared";
import { MODEL_INTELLIGENCE_LAST_VERIFIED, openRouterOperationalFacts, artificialAnalysisFacts, benchmarkClaimFact, arenaSource, designArenaSource, fact, openRouterSource, vercelOperationalFacts } from "../shared";

export const WORKHORSE_REGISTRY_ENTRIES: readonly ModelIntelligenceModel[] = [
  {
    id: "google/gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image,file,audio,video->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 1_048_576,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 1_048_576,
        inputPricePerMillion: 2,
        outputPricePerMillion: 12,
      }),
      benchmarkClaimFact({
        metricId: "arena_text_overall_rank",
        label: "Arena Text Overall rank",
        value: 5,
        unit: "rank",
        source: arenaSource("/leaderboard/text/overall-no-style-control", "Arena AI - Text Arena Overall"),
      }),
      benchmarkClaimFact({
        metricId: "arena_document_rank",
        label: "Arena Document rank",
        value: 7,
        unit: "rank",
        source: arenaSource("/leaderboard/document", "Arena AI - Document Arena"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_code_categories_elo",
        label: "DesignArena Code Categories Elo",
        value: 1321,
        unit: "elo",
        source: designArenaSource("/leaderboard/code", "DesignArena - Code Categories"),
        note: "DesignArena's public leaderboard API returns internal model id `riftrunner`; the site maps that id to the Gemini 3 Pro Preview model page in its client code.",
      }),
      benchmarkClaimFact({
        metricId: "designarena_website_elo",
        label: "DesignArena Website Elo",
        value: 1323,
        unit: "elo",
        source: designArenaSource("/leaderboard/website", "DesignArena - Website"),
        note: "DesignArena's public leaderboard API returns internal model id `riftrunner`; the site maps that id to the Gemini 3 Pro Preview model page in its client code.",
      }),
      benchmarkClaimFact({
        metricId: "designarena_ui_component_elo",
        label: "DesignArena UI Component Elo",
        value: 1356,
        unit: "elo",
        source: designArenaSource("/leaderboard/ui-components", "DesignArena - UI Components"),
        note: "DesignArena's public leaderboard API returns internal model id `riftrunner`; the site maps that id to the Gemini 3 Pro Preview model page in its client code.",
      }),
    ],
    lenses: [
      {
        lens: "overall_quality",
        rank: 6,
        rationale: "Strong frontier generalist when you want Gemini Pro depth at lower cost than the Anthropic and OpenAI premium flagships.",
      },
      {
        lens: "long_context",
        rank: 5,
        rationale: "1M-class context and strong document ranking make it a solid depth-first alternative beneath Gemini 3.1 Pro Preview.",
      },
      {
        lens: "frontend_ui",
        rank: 4,
        rationale: "Strong frontend and website performer in DesignArena, with especially good UI component results under DesignArena's Gemini 3 Pro Preview mapping.",
      },
    ],
    derived: {
      taskFamilies: ["general", "research", "long_context", "multimodal", "agentic_coding"],
      strengths: ["Strong 1M-context multimodal reasoning", "Good document performance", "Useful premium-middle Gemini option", "Strong website and UI benchmark performance"],
      caveats: ["Preview model", "Not as strong as Gemini 3.1 Pro Preview on the latest leaderboard snapshot"],
      whenToUse: "High-context multimodal reasoning, document analysis, frontend implementation, and agentic work when you want Gemini Pro quality without forcing the very top-end 3.1 Pro lane.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "premium",
        quality: 3,
        speed: 2,
        cost: 0,
        reliability: 3,
      },
    },
  },
  {
    id: "google/gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image,file,audio,video->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 1_048_576,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 1_048_576,
        inputPricePerMillion: 0.5,
        outputPricePerMillion: 3,
      }),
      ...artificialAnalysisFacts({
        slug: "gemini-3-flash",
        label: "Artificial Analysis - Gemini 3 Flash Preview",
        intelligenceIndex: 35,
        outputTps: 176.8,
        ttftSeconds: 1.19,
        note: "Artificial Analysis benchmarks the Gemini 3 Flash Preview non-reasoning page variant.",
      }),
      benchmarkClaimFact({
        metricId: "arena_text_overall_rank",
        label: "Arena Text Overall rank",
        value: 9,
        unit: "rank",
        source: arenaSource("/leaderboard/text/overall-no-style-control", "Arena AI - Text Arena Overall"),
      }),
      benchmarkClaimFact({
        metricId: "arena_search_grounding_rank",
        label: "Arena Search grounding rank",
        value: 3,
        unit: "rank",
        source: arenaSource("/leaderboard/search/overall-add-style-control", "Arena AI - Search Arena"),
        note: "The live Arena row is for the grounding-specific variant `gemini-3-flash-grounding`, used here as a capability signal rather than a deployable gateway ID.",
      }),
    ],
    lenses: [
      {
        lens: "multimodal",
        rank: 1,
        rationale: "Best balance of multimodal breadth, 1M context, quality, and speed in the refreshed Gemini set.",
      },
      {
        lens: "ttft",
        rank: 3,
        rationale: "Strong low-latency multimodal option without dropping all the way to a classifier-tier model.",
      },
      {
        lens: "throughput",
        rank: 3,
        rationale: "High measured throughput for an affordable multimodal long-context model.",
      },
    ],
    derived: {
      taskFamilies: ["general", "research", "long_context", "multimodal", "support", "coding"],
      strengths: ["Fast multimodal workhorse", "1M context", "Strong speed-quality tradeoff"],
      caveats: ["Below Gemini 3.1 Pro on the hardest reasoning", "Pricier than Flash Lite for classifier-heavy volume"],
      whenToUse: "Fast multimodal, long-context, and interactive agent workflows when you want stronger quality than budget-tier classifiers.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "efficient",
        quality: 2,
        speed: 3,
        cost: 2,
        reliability: 2,
      },
    },
  },
  {
    id: "google/gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text,image,file,audio,video->text",
    openSource: false,
    structuredOutput: true,
    toolUse: true,
    vision: true,
    contextWindow: 1_048_576,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 1_048_576,
        inputPricePerMillion: 0.25,
        outputPricePerMillion: 1.5,
      }),
      ...artificialAnalysisFacts({
        slug: "gemini-3-1-flash-lite-preview",
        label: "Artificial Analysis - Gemini 3.1 Flash-Lite Preview",
        intelligenceIndex: 34,
        outputTps: 249.3,
        ttftSeconds: 6.71,
        note: "Artificial Analysis benchmarks the Gemini 3.1 Flash-Lite Preview page variant.",
      }),
    ],
    lenses: [
      {
        lens: "classifier_candidate",
        rank: 2,
        rationale: "Best cheap multimodal classifier and extractor in the registry when you still want 1M context and broad input coverage.",
      },
      {
        lens: "throughput",
        rank: 2,
        rationale: "One of the fastest measured low-cost models in the registry while preserving multimodal coverage.",
      },
    ],
    derived: {
      taskFamilies: ["general", "support", "multimodal", "long_context", "coding"],
      strengths: ["Cheap multimodal workhorse", "High measured output speed", "1M context with structured outputs"],
      caveats: ["Measured TTFT is slower than the older Flash Lite generation", "Lower ceiling than Pro on subtle reasoning"],
      whenToUse: "Budget-first classifier, extraction, translation, and high-volume multimodal routing work.",
      profileBuilder: {
        contextBand: "ultra",
        costTier: "budget",
        quality: 2,
        speed: 3,
        cost: 3,
        reliability: 2,
      },
    },
  },
  {
    id: "nvidia/nemotron-3-super-120b-a12b",
    name: "NVIDIA Nemotron 3 Super",
    supportedGateways: ["openrouter"],
    modality: "text->text",
    openSource: true,
    structuredOutput: true,
    toolUse: true,
    vision: false,
    contextWindow: 262_144,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 262_144,
        inputPricePerMillion: 0.1,
        outputPricePerMillion: 0.5,
      }),
      ...artificialAnalysisFacts({
        slug: "nvidia-nemotron-3-super-120b-a12b",
        label: "Artificial Analysis - NVIDIA Nemotron 3 Super",
        intelligenceIndex: 36,
        outputTps: 456.2,
        ttftSeconds: 0.78,
        note: "Artificial Analysis benchmarks the reasoning page variant. Artificial Analysis and OpenRouter's public Nvidia page describe a 1M context window, but the live OpenRouter models API currently resolves this deployable ID to 262,144 tokens on 2026-03-21.",
      }),
    ],
    lenses: [
      {
        lens: "classifier_candidate",
        rank: 1,
        rationale: "Best current OpenRouter-only classifier candidate on price, TTFT, throughput, and enough context headroom for the router prompt.",
      },
      {
        lens: "throughput",
        rank: 2,
        rationale: "Second-fastest text model in the registry by measured output speed, while staying cheaper and lower-latency than frontier-mini alternatives.",
      },
      {
        lens: "budget_text",
        rank: 2,
        rationale: "Excellent speed-quality-value tradeoff for hot-path routing, extraction, and operational text work.",
      },
    ],
    derived: {
      taskFamilies: ["general", "support", "coding", "research"],
      strengths: ["Excellent classifier economics", "Very high measured throughput", "Low TTFT", "Open weights with tool use"],
      caveats: ["OpenRouter-only exact ID", "Text-only deployable ID", "OpenRouter's live API currently exposes 262K context despite separate 1M context claims on benchmark and provider pages"],
      whenToUse: "Fast, cheap text classification, routing, extraction, and operational reasoning when you want stronger quality than the cheapest budget models without paying frontier-mini prices.",
      profileBuilder: {
        contextBand: "long",
        costTier: "budget",
        quality: 2,
        speed: 3,
        cost: 3,
        reliability: 2,
      },
    },
  },
  {
    id: "deepseek/deepseek-v3.2",
    name: "DeepSeek V3.2",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text->text",
    openSource: true,
    structuredOutput: true,
    toolUse: true,
    vision: false,
    contextWindow: 163_840,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 163_840,
        inputPricePerMillion: 0.26,
        outputPricePerMillion: 0.38,
      }),
      ...artificialAnalysisFacts({
        slug: "deepseek-v3-2",
        label: "Artificial Analysis - DeepSeek V3.2",
        intelligenceIndex: 32,
        outputTps: 33,
        ttftSeconds: 1.83,
        note: "Artificial Analysis benchmarks the non-reasoning page variant.",
      }),
    ],
    lenses: [
      {
        lens: "budget_text",
        rank: 1,
        rationale: "Best ultra-cheap text model in the shortlist while still carrying meaningful AA intelligence.",
      },
      {
        lens: "open_source",
        rank: 5,
        rationale: "Open-weight budget option for teams that want deployable open models over premium proprietary ones.",
      },
    ],
    derived: {
      taskFamilies: ["general", "coding", "support"],
      strengths: ["Very cheap text volume", "Open weights", "Respectable AA intelligence for the price"],
      caveats: ["Low throughput versus other fast models", "No native vision in this deployable ID"],
      whenToUse: "Budget-first text work, background tasks, and large-volume routing pools where output cost matters most.",
      profileBuilder: {
        contextBand: "standard",
        costTier: "budget",
        quality: 2,
        speed: 1,
        cost: 3,
        reliability: 2,
      },
    },
  },
  {
    id: "z-ai/glm-5",
    name: "GLM 5",
    supportedGateways: ["openrouter", "vercel"],
    modality: "text->text",
    openSource: true,
    structuredOutput: true,
    toolUse: true,
    vision: false,
    contextWindow: 80_000,
    lastVerified: MODEL_INTELLIGENCE_LAST_VERIFIED,
    metrics: [
      ...openRouterOperationalFacts({
        contextWindow: 80_000,
        inputPricePerMillion: 0.72,
        outputPricePerMillion: 2.3,
      }),
      ...artificialAnalysisFacts({
        slug: "glm-5",
        label: "Artificial Analysis - GLM-5",
        intelligenceIndex: 50,
        outputTps: 89.3,
        ttftSeconds: 1.45,
        note: "Artificial Analysis benchmarks the GLM-5 reasoning page variant.",
      }),
      benchmarkClaimFact({
        metricId: "designarena_code_categories_elo",
        label: "DesignArena Code Categories Elo",
        value: 1337,
        unit: "elo",
        source: designArenaSource("/leaderboard/code", "DesignArena - Code Categories"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_website_elo",
        label: "DesignArena Website Elo",
        value: 1330,
        unit: "elo",
        source: designArenaSource("/leaderboard/website", "DesignArena - Website"),
      }),
      benchmarkClaimFact({
        metricId: "designarena_ui_component_elo",
        label: "DesignArena UI Component Elo",
        value: 1360,
        unit: "elo",
        source: designArenaSource("/leaderboard/ui-components", "DesignArena - UI Components"),
      }),
    ],
    lenses: [
      {
        lens: "open_source",
        rank: 1,
        rationale: "Best current open-weight general-purpose model in the registry, with strong coding and agentic positioning.",
      },
      {
        lens: "coding_quality",
        rank: 4,
        rationale: "High-end open-weight coding and agentic model when you want stronger judgment than cheaper open models.",
      },
      {
        lens: "frontend_ui",
        rank: 3,
        rationale: "Best current open-weight frontend/UI model in the registry, with DesignArena's #2 UI component result and top-four website performance.",
      },
    ],
    derived: {
      taskFamilies: ["coding", "agentic_coding", "general", "research"],
      strengths: ["Strong open-source flagship", "Agentic engineering focus", "Fast enough for iterative coding loops", "Strong frontend/UI benchmark performance"],
      caveats: ["80K context is much shorter than Gemini or Grok long-context options", "Text-only deployable ID"],
      whenToUse: "Open-weight coding, frontend implementation, agentic engineering, and expert text work when you want a strong model without relying on closed frontier vendors.",
      profileBuilder: {
        contextBand: "standard",
        costTier: "efficient",
        quality: 3,
        speed: 2,
        cost: 2,
        reliability: 2,
      },
    },
  },
];
